### ISSUE TITLE
[BUG] Drawers do not have boxes.

### ISSUE THREAD

**Issue by Monniasza** [ostat/gridfinity_extended_openscad#10]
When I enable baseplates on the drawer, the drawer does not have the bottom base, but throws a warning: `Ignoring unknown module 'grid_block'`. Please revert the base STL and my work workaround with tiling the base model. Also please merge the efficient shelves that I've made after you merged the PR.

**Comment by ostat** [comment]
This should be fixed. Can you get latest and let me know if you are still having issues?
I also added some filament saving options to the walls. Feedback welcome.
I would like to avoid requiring the STL unless we absolutely need to. As it reduces the options, like setting the base to half pitch.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/9eae0cd2-f1a4-42b6-bb1d-229393c7f760)

**Comment by Monniasza** [comment]
It's okay. I'll check out the options. I'm using OpenSCAD version 2023.08.29 snapshot.

**Comment by Monniasza** [comment]
The pattern extends past the front and starts too far to the front.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/37037712/85309435-624d-4ebd-8c9c-b75aa5dbf5dc)

**Comment by Monniasza** [comment]
Here are my settings:
[gridfinity_drawers.json](https://github.com/ostat/gridfinity_extended_openscad/files/14319404/gridfinity_drawers.json)

**Comment by Monniasza** [comment]
On the left side of the drawer on the rear there should not be hex pattern.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/37037712/81d6f80a-8477-47d4-986c-002f99baf82c)

**Comment by ostat** [comment]
I will take a look. I had shift the side cutout to stop it going out the back. 

Good spot re the back will verify the math. 

Not sure if you saw, I added an option to the drawers to remove the floor and just have the grid. If you fill it with bins you might not need the solid floor. Need to check if the bins would stick through and mess up the sliding action.

**Comment by ostat** [comment]
The wall coutout positioning is fixed in d64e655

**Comment by Monniasza** [comment]
@ostat The wall cutout positioning looks good.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/37037712/af5675bc-5c2c-4e69-882f-f293ea3d62c9)

**Comment by Monniasza** [comment]
However, the model with hex pattern takes forever to slice on PHOEU computer.

**Comment by ostat** [comment]
I updated the model to allow for custom drawer sizer. It was more complex than expected, but I think I got there in the end. Would appreciate if you could review the changes in case I broke anything.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/60a9a28a-336c-4ef8-8a5f-58741e5daeb3)

**Comment by Monniasza** [comment]
I get lots of warnings and the drawer boxes do not appear, only the handles.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/37037712/22cd1600-f500-40f2-a73e-8e1c21b378b2)
https://gist.github.com/Monniasza/8cce959ca7d661030b4a5329b9eec068

**Comment by Monniasza** [comment]
Additionally, the drawerslides should only extend so far as the user has defined, but they always cover the entire width of the chest.

**Comment by Monniasza** [comment]
You can define the inner dimensions of the drawers as a list.

**Comment by ostat** [comment]
Sorry had not pushed all the changes. Think I got them all now.

**Comment by Monniasza** [comment]
@ostat You have not said that setting drawer handle height to -1 makes it span the entire drawer height.

**Comment by Monniasza** [comment]
Vertical handles do not require supports, unlike horizontal handles.

**Comment by ostat** [comment]
We can prob close this now? I think all the issues are resolved. 
 
I have a couple of other ideas. 

I would like an option to swap drawers around when they are not the same size. Perhaps a small set (every 7mm) of runners that slides in to the walls of the drawer or chest? Though I'm a bit worried that the walls of the chest will flex too much. 

Also I would like an option to have the chest fit in to the shape of a Gridfinity bin. But maybe this would need to be a different script, as it would confuse the settings.
