### ISSUE TITLE
Feature Request: basic cup wall cutout location

### ISSUE THREAD

**Issue by benlangfield** [ostat/gridfinity_extended_openscad#14]
Would love the ability to move the location of the wall cutouts on the basic cup.  Currently they default to the centre of the bin and can't be moved.  I would like to be able to specify the location, for example, 2 grids or perhaps 80mm from the end of the x-axis.

This would be very handy for cutlery bins for kitchen drawers.  The wall gaps need to be lined up regardless of bin size for these as they are all sitting side by side, making it easier to get your finger in to grab a spoon sort of thing.

**Comment by ostat** [comment]
I have changed the logic for the cutout option in changeset d5a8a1e.

The walls option used to turn on each wall at the center position. 
No we can use those value to change the position:

- 0: disables the cutout on that wall.
- Positive numbers: sets the position in Gridfinity units (42mm). 
  - I am considering supporting both GF units and mm. If the number is greater than the length of the wall in GF units, assume its mm.
- Negative numbers: position it using a ratio of `length/abs(value)`. I.E. -2 results in 1/2.

Its not that well tested, but I think it should do what we want.

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/3c6a8997-31fa-4016-bb31-d54d9e4bd453)

**Comment by benlangfield** [comment]
This is exactly what I wanted, thank you! 

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/122901169/1a61a1e4-0cdd-4038-9539-9b093b204d79)

Couldn't work out how to change the width, but wallcutout width of 0 seems about right anyway.

**Comment by benlangfield** [comment]
This is exactly what I wanted, thank you!

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/122901169/05611f92-3bf6-4171-9b83-7013f30909e7)

Couldn't work out how to change the width, but wallcutout width of 0 seems about right anyway.

**Comment by ostat** [comment]
setting the `wallcutout width` to a number other than 0 will make the cutout the desired width. using 0 will use the `walllength/2`.
Is that not working for you?
