### ISSUE TITLE
variable center not specified as parameter for gridfinity_silverware.scad

### ISSUE THREAD

**Issue by ph15h** [ostat/gridfinity_extended_openscad#2]
opening gridfinity_silverware.scad outputs this error. 

```WARNING: variable center not specified as parameter in file gridfinity_silverware.scad, line 139```
the object output with this error is below.

![openscad - 2023-12-13 13-01-13](https://github.com/ostat/gridfinity_extended_openscad/assets/50638066/bc742325-5761-45f1-b551-cb2c17d365cf)

**Comment by ostat** [comment]
Thanks for letting raising. This has been fixed by 3747e7c.
