### ISSUE TITLE
Support / tip jar / coffee link?

### ISSUE THREAD

**Issue by jprisant** [ostat/gridfinity_extended_openscad#24]
I can't seem to find a tip jar for this project anywhere. Forgive me if I am overlooking something wildly obvious.

This project is so incredibly useful... you have no idea how much I appreciate it!

**Comment by ostat** [comment]
done, its on the project page. 
I appreciate the offer, but you don't need to support me. Glad you like the project.

**Comment by jprisant** [comment]
Which project page?

**Comment by ostat** [comment]
https://github.com/ostat/gridfinity_extended_openscad

Its on the right side. 

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/f093c4f9-c662-4281-8427-5f30ee2ea052)

**Comment by jprisant** [comment]
Thanks. It isn't much, but on principle... I like to support creators. Thank again for this project!

**Comment by ostat** [comment]
Thanks mate. Very kind of you.
