### ISSUE TITLE
Extension tabs incorrectly positioned

### ISSUE THREAD

**Issue by jpypi** [ostat/gridfinity_extended_openscad#26]
Using `gridfinity_basic_cup.scad` and setting `position` to either "center" or "zero" (as opposed to the default: "default") and then with `extention_tabs_enabled = true` and either `extention_x_enabled = true` or `extention_y_enabled = true`, the extension tabs end up getting placed as separate pieces from the main bin.

This is just one example, but the different values of position and extension (x or y) put the tabs is various different places.
![screenshot](https://github.com/ostat/gridfinity_extended_openscad/assets/4681365/879df649-66d8-41b6-a730-2fd846268766)

**Comment by ostat** [comment]
Hi thanks for reporting this. I think this was a bug while I was trying to rework the tabs.
I believe it was fixed in 9e79f20. Would you be able to get latest and retry?

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/cae12142-a93e-4f9c-9424-a3f90b273111)

**Comment by jpypi** [comment]
Pulled latest... still the same issue.

**Comment by ostat** [comment]
Hi, Sorry I misunderstood this issue. Its now fixed. Thanks for raising
