### ISSUE TITLE
wallpattern doesn't work with thick chamber divider walls

### ISSUE THREAD

**Issue by jpypi** [ostat/gridfinity_extended_openscad#27]
When trying to use `wallpattern` on the chamber divider walls (i.e. `wallpattern_enabled=true` and `wallpattern_dividers_enabled=true`) the pattern works only when the `chamber_wall_thickness` is less than or equal to `2 * wall_thickness`. So, if `wall_thickness=0.95` the pattern won't show up if `chamber_wall_thickness > 1.9`. The preview of the render looks glitchy when `chamber_wall_thickness` is exactly equal to `2 * wall_thickness` Example pictures are below:

Normal:
![normal](https://github.com/ostat/gridfinity_extended_openscad/assets/4681365/b755c5da-866d-43da-8ee5-98535bcd3515)

When wall thickness is exactly 2x:
![exactly2x](https://github.com/ostat/gridfinity_extended_openscad/assets/4681365/a62dfd54-cf06-4231-9fc9-bd4f00af595b)

Just a tiny bit more than 2x:
![2x+1](https://github.com/ostat/gridfinity_extended_openscad/assets/4681365/7c8d22ae-3095-4328-b1b9-2420b7cf884e)

Just a little bit less than 2x:
![2x-1](https://github.com/ostat/gridfinity_extended_openscad/assets/4681365/4b685199-c9e4-42d9-9007-fb5c682d8447)

**Comment by ostat** [comment]
Thanks for submitting so much detail 
This has been fixed in 35b4281. I was using the wall width not separator width.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/1a2b2f5e-18fe-4559-8e4a-c2249fc7b9b2)
