### ISSUE TITLE
Allow non full sizes baseplates to fill the space in a drawer

### ISSUE THREAD

**Issue by ostat** [ostat/gridfinity_extended_openscad#28]
Drawers will often not fit an exact gridfinity 42 unit size.
allow some options to allow the extra space to be filled.

**Comment by ostat** [comment]
Updated the width and depth options to allow entering the size in GF units or in mm.
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/e27ccf45-8fce-4ca8-8229-7c3828d9b041)

Added option to all the incomplete grid to filled, or cropped.

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/bb9d2d6d-ae2b-4bfa-9a4e-afd6ba50fc53)
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/138ab03b-a91d-4e94-8b46-3c913522601e)

**Comment by Monniasza** [comment]
This issue is misspelled.

**Comment by ostat** [comment]
fixed in 8b19740
