### ISSUE TITLE
Magnet stress and removal groove

### ISSUE THREAD

**Issue by BreakMate** [ostat/gridfinity_extended_openscad#31]
I just want to start by saying, WOW! This resource is amazing for making custom gridfinity bins.

I wanted to request making a small addition to the magnet holes. If there is a small enough groove, this would allow for easier insertion and removal of the magnets. This can be applied to both the bins as well as the base, although I havent tested it with the base. I would add them myself, but I am horrid with openscad, but I was able to test this in Freecad with great success. Could you add a parameter to implement this?
![Screenshot 2024-06-28 142946](https://github.com/ostat/gridfinity_extended_openscad/assets/137567806/0088a3cc-1c49-482f-80c3-8622ff519481)
![Screenshot 2024-06-28 143008](https://github.com/ostat/gridfinity_extended_openscad/assets/137567806/815db4d5-58cb-408f-aeab-850696fef7e1)

**Comment by ostat** [comment]
This is an interesting idea. I'm sure it can be added. 
Do you think we could angle it in to the corner?
My reason is the efficient bases. Those support magnets and have a cap that goes over the magnet. If we angle it in to the corner we won't need to change the cap.

**Comment by BreakMate** [comment]
![20240630_175957](https://github.com/ostat/gridfinity_extended_openscad/assets/137567806/cfb152e4-482a-4ad1-8b31-a35630d6bf29)

Good point! And quite a good feature, the efficient floor. I redrew the gaps and it still works! I made the straight part 1.5mm and the diameter of the groove 1.3mm. The magnets are 6mm and I made the holes in my model 6mm

**Comment by BreakMate** [comment]
Using Prusaslicer to slice, MK4 with a 0.4 nozzle to print.

My initial reason for avoiding the outer corners was to reduce the chance of curling on the edges

**Comment by ostat** [comment]
That looks good. Nice work getting it printed so fast. 
I agree that pointing to the centre would be more stable. 
I could direction it based on the selected floor type, efficient floors to the corner and smaller, otherwise to the centre and a bit bigger. 
Do you have thoughts on the relief size for different sized magnets?

**Comment by BreakMate** [comment]
I do notice in your parameters, there is a hard cutoff of how close the magnets can get to the side of the base. not sure what that value is, but could be worked around.
If the magnets get smaller, then maybe it would hold better if the groove shrinks slightly. Making it too small would make it more difficult to fish it out (in the picture you can see the pick I'm using). Shouldn't be too big of an issue

If the efficient floor would account for the groove towards the center, I think that might work out the best and reduce the chance of curling.

**Comment by BreakMate** [comment]
![20240630_202549](https://github.com/ostat/gridfinity_extended_openscad/assets/137567806/836c0688-35c6-40a4-bd50-8c27919d8466)
![20240630_202554](https://github.com/ostat/gridfinity_extended_openscad/assets/137567806/349e77f5-4158-4e5e-b490-3d91838fd237)

I love the efficient floor still able to use magnets, but I cant get them out now LOL

**Comment by ostat** [comment]
I had a quick go at this tonight. 
I am bit sick so it needs a bit of work to get it working better and covering different sized magnets better. Also I have not tired to print this.

The code is pushed to the main branch.

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/5c3aa616-b7b5-440b-8f05-c51d5e950b08)
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/8d63c230-1ba6-4e4a-bb87-9b23e90be846)

**Comment by BreakMate** [comment]
![20240701_154138](https://github.com/ostat/gridfinity_extended_openscad/assets/137567806/e9159391-4124-44c3-b282-3f882f239c59)
It works swell! 
I printed this with PETG in an enclosure. I've found that all gridfinity bins print better in an enclosure. It practically eliminates all warping. The black one I printed earlier I printed with PLA without an enclosure and the house fan was running, minor warping but enough to notice.

**Comment by ostat** [comment]
Couple of questions;
Do you think this is good to close?

Based on your testing what are the recommend settings with the relief on and off?
The original design was to use 6.5mm diameter for a 6mm magnet, we add 0.1mm to the depth.
I would like to document recommendations for people.
Are the magnets sitting prod, in that image, do we need to recommend adding some extra depth for sagging of the bridge?

**Comment by BreakMate** [comment]
I have never thought that 6.5mm was good for 6mm magnets (unless you mean for glue). When there are just magnet holes, 6.1 seems to do the trick. Thanks to this relief, I can make the magnet holes exactly 6 millimeters. It goes in with pressure, so I know that it won't come out easily.

As for the magnet protrusions, I believe that part of the problem comes from the efficient floor. The flex that is generated when trying to push in the magnets is causing them not to fully seat the first time around. Pressure must be applied from both sides. I haven't tested this with PLA, only PETG.

Magnet depth must be controlled by the user. I personally like 2.4 millimeters depth for a 2 millimeter magnet, probably due to overhangs. If overhangs are to be avoided, maybe add a version of the overhang remedy that only is meant to make bridges without necessarily making a hole.

Im in vegas currently, will be back thursday for more printed tests.

**Comment by BreakMate** [comment]
Ok, so I found out that my magnets are actually 2.2 mm, so makes sense why 2.4mm height always worked well for me.

**Comment by BreakMate** [comment]
![20240709_224828.jpg](https://github.com/ostat/gridfinity_extended_openscad/assets/137567806/ddeb77c4-49cd-43e5-8b61-4e6b611db15d)

It is kinda thin, maybe 1~2 more layers would be better

**Comment by ostat** [comment]
That should be configurable as the floor thickness. Do you know what value was used? I would double check see if there are any bugs in the floor thickness and the clearance height calculations.

**Comment by rwgunther** [comment]
I'm experiencing adhesion problems with the grooves pointing out to the corners. I have to use brims to print these without the corners curling. I don't seem to experience that as much when I don't include the grooves, but I definitely like having them!

**Comment by ostat** [comment]
@rwgunther, I have change the `magnet release` option from a boolean (on/off) to a dropdown where you can select if you want the relief to point in or out. I think pointing in should resolve the adhesion issue you were having? Please let me know how it goes if you test it.
`Auto`, will point out for `efficient floor = on`, and in for `efficient floor = off`.

![image](https://github.com/user-attachments/assets/9e51409b-6bca-481d-8742-a1fa56831602)

**Comment by rwgunther** [comment]
This looks great. I'll try it out on my next print!

**Comment by ostat** [comment]
Close as I think this is good now.
