### ISSUE TITLE
chest efficient back should cut per shelf

### ISSUE THREAD

**Issue by trysten** [ostat/gridfinity_extended_openscad#36]
[Efficient Back](https://github.com/ostat/gridfinity_extended_openscad/blob/8d511b6b2fc00955bb35ebd1b724416cffa3ea42/gridfinity_drawers.scad#L78) is a great idea. Considering that users will likely print drawer chests pointing upwards, efficient back should cut out per shelf, eliminating the bridges pictured. Thank you for this awesome project

![image](https://github.com/user-attachments/assets/74b765ac-c7b6-4de2-b896-e8383d8e4943)
![image](https://github.com/user-attachments/assets/9908dc28-9713-4038-a312-350743089c52)

**Comment by ostat** [comment]
Oh, that looks like a bug. The back cutout looks rotated. Will take a look thanks.

**Comment by ostat** [comment]
This has been fixed in commit 3681ebc

**Comment by ostat** [comment]
This has been fixed in commit 3681ebc
