### ISSUE TITLE
Wall pattern does not apply to dividers.

### ISSUE THREAD

**Issue by brotherssmith** [ostat/gridfinity_extended_openscad#4]
I don't see the setting listed in the documentation, but there is a checkbox in the program, and it seems to do nothing. Have tried changing various wall pattern and divider settings to no effect.

Unrelated - also having the missing variables issue for baseplate generation, restoring the old variable names remedied some issues, but the missing Sdix remains for me, and it won't generate a full grid unless in baseplate also a lid mode.

Feature request - A baseplate/lid that is a "lite" version, missing magnet holes for efficiency.
Example here - https://www.thingiverse.com/thing:5975756

Thanks for all the work you've put into this already.

**Comment by ostat** [comment]
>I don't see the setting listed in the documentation, but there is a checkbox in the program, and it seems to do nothing. Have tried changing various wall pattern and divider settings to no effect.
This was a bug introduced when I rewrote the new divider logic. Its been fixed, but its only setup to work for the **Vertical chambers** option at the moment. 
fixed in e16e486
![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/5a7e30fe-90d7-4ebf-b348-24afcf2abf20)

>Unrelated - also having the missing variables issue for baseplate generation, restoring the old variable names remedied some issues, but the missing Sdix remains for me, and it won't generate a full grid unless in baseplate also a lid mode.
I believe this was covered in #1, its fixed now

>Feature request - A baseplate/lid that is a "lite" version, missing magnet holes for efficiency.
>Example here - https://www.thingiverse.com/thing:5975756
Moved out to its own issue. #5

**Comment by natalietrinh102** [comment]
Are there plans to support horizontal dividers? Only supporting vertical dividers leads to some odd label positioning.

**Comment by ostat** [comment]
> Are there plans to support horizontal dividers? Only supporting vertical dividers leads to some odd label positioning.  

We do support horizontal dividers. However we don't support the patterned wall on horizontal dividers. This is beachside I would need to deal with the intersection area when both are enabled. 
Not sure I follow how this impacts the labels?

**Comment by natalietrinh102** [comment]
I meant support for patterned walls on horizontal dividers. The labels positions currently don't allow for you to build a model with the label on the short side while having a patterned wall:

![debug1](https://github.com/ostat/gridfinity_extended_openscad/assets/34173043/42c4e3c0-2851-42c4-8182-9b1120d48ad4)
This is what I'm intending to do - with a patterned wall in the middle

![debug2](https://github.com/ostat/gridfinity_extended_openscad/assets/34173043/132722cf-eaf6-4024-9eba-9eca588fc63d)
This is the orientation that allows for a patterned wall - but the label is now on a side that I won't use. (There is also some odd geometry on vertical chamber in this case)

For now I've just exported it into a CAD program and created the pattern myself, but adding it would be useful for me in the future.

**Comment by ostat** [comment]
We can do that.

**Comment by ostat** [comment]
Fixed in e92073d .

![image](https://github.com/ostat/gridfinity_extended_openscad/assets/2128234/99ddef58-8712-4497-a5eb-283cfabefc66)

**Comment by ostat** [comment]
this issue is resolved
