### ISSUE TITLE
wall pattern fill not following label

### ISSUE THREAD

**Issue by wedgen** [ostat/gridfinity_extended_openscad#42]
I moved the label to "back" and noticed the fill of the wall pattern didn't follow the label like i expected.  Looked at the code but didn't notice what controls that fill.  Will keep looking.  

<img width="728" alt="openscad_cbrb5GNANm" src="https://github.com/user-attachments/assets/730c5052-687d-4157-ac02-026bb876c4a5">

**Comment by ostat** [comment]
This has been fixed 722b6c6
thanks for raising 

![image](https://github.com/user-attachments/assets/a5bd7492-ac6a-4b57-a5f3-f1fb0e73b26d)
