### ISSUE TITLE
wall pattern inconsistent for wall cutout length ratio (neg value) 

### ISSUE THREAD

**Issue by wedgen** [ostat/gridfinity_extended_openscad#43]
![image](https://github.com/user-attachments/assets/0e7a2487-bd1b-4952-a637-4e1ca79e8651)

using the ratio option for wall cutouts do not produce the same patterns as GF units

**Comment by ostat** [comment]
This has been fixed in 636b832.
Thanks for raising

![image](https://github.com/user-attachments/assets/481db650-6f6e-4002-8d36-0a6c2f25d03f)
