### ISSUE TITLE
Click Labels do not fit

### ISSUE THREAD

**Issue by lsd87** [ostat/gridfinity_extended_openscad#53]
When printed the click/snap labels do not fit into the recess, It looks like the recess goes back to far.
Adjusting the zclearance does not help.

The Left cup is the current version, the right is the old version which works
![IMG_20241008_140339](https://github.com/user-attachments/assets/ee306d59-51d8-4be5-82f4-71da12177aa4)
The scad file below does work, I think its one of your older versions 17/2/2024
 
[gridfinity_basic_cup_simplified.zip](https://github.com/user-attachments/files/17292812/gridfinity_basic_cup_simplified.zip)

**Comment by lsd87** [comment]
Bit of testing
If you set the lip style to reduced/minimum/not stackable then you can see the full recess, printed the not stackable version and the click/snap label fits fine. 
Set to reduced lip and zone in 
![image](https://github.com/user-attachments/assets/62242a6e-df08-4da7-8ad4-fd27bb9bff0f)
Then select normal and see the lip "eat" into the label platform at the back
![image](https://github.com/user-attachments/assets/1f79a33d-4102-4ba0-8499-7c8714ec9d4f)

**Comment by lsd87** [comment]
A work around is to set the label depth to 16.5mm or more so that the curves of the back wall don't eat into the label recess.
Also setting zclearance to 1.0mm helps with stacking

**Comment by lsd87** [comment]
I had a look at the old simplified SCAD cup that I printed and the whole label platform does not touch the inner edge lip because on the latest cups there's an extra lip I assume for better stacking.
So I printed another cup with the zclearance set to 3mm, this made the click label fit.
When label style is normal, the label relief can be used to lower the insert part of the platform but when click style is set, the relief setting does not work, that's why I had to use the zclearance

This is how the lip/platform connect with zclearance set to 0
![image](https://github.com/user-attachments/assets/2fb938b7-6cad-4e4d-aa17-02c639298236)

And this is when its set to +3
![image](https://github.com/user-attachments/assets/b55c1a94-a16a-4f05-9f5e-73019236de5d)

The problem with labels is that there appears to be at least 4 types, I would like to use ndevenish great gflabel program so that I can make up any label I need without looking around the internet to see if someone else has created one using fusion/freecad ...etc
[https://github.com/ndevenish/gflabel#label-bases](url)

The pred labels don't appear to fit because the tabs need a slot in the cup edge to fit in (may be able to shrink using the --width option in gflabel), the predbox and plain might work but I liked the cullen/webb labels because they would be easy to change

I think its best to stick with the standard size (is there one) label initially. but with your version allows a user to adjust the width/size of the platform AND the recess. that way all variations could be covered.

As for click settings default 
First does the zclearance just alter the location of the label platform ? if so, it needs to be under the Label settings section
Second can you put a note to say "if you use click, set zclearance to say 3mm" or something like it or 
setting click sets the zclearance to +3 automatically

Sorry can't think of a good fix,  too many variables and I know nothing about SCAD

**Comment by lsd87** [comment]
Sorry about the close/reopen, clicked on the wrong button hoh

**Comment by lsd87** [comment]
I think the main problem is with the lip style
If the click recess is supposed to be 36.7mm, then using the normal lip, I read 36mm between the lip, therefore the click label will not fit. Same for the depth, 11.3 label won't fit in a 10mm recess. 
Its either not use the normal lip or move the label platform down below the curved lip about 2mm or more zclearance

Normal lip
![image](https://github.com/user-attachments/assets/6a0aed42-c3f4-46d3-8bcc-3ad36de16775)

Reduced lip
![image](https://github.com/user-attachments/assets/9a2fd9a9-6b54-41f0-8682-9e684c6002e1)


Normal lip plus 2mm
![image](https://github.com/user-attachments/assets/75c34bf0-a3a8-4294-99fd-827e5b902a88)


BTW. Assume you know about the Line 177 error
[WARNING: variable extension_enabled not specified as parameter in file gridfinity_basic_cup.scad, line 177](https://github.com/ostat/gridfinity_extended_openscad/issues/177,D:/lsd/Downloads/gridfinity_extended_openscad-main%2015th%20Oct/gridfinity_extended_openscad-main/gridfinity_basic_cup.scad)
[WARNING: variable extension_tabs_enabled not specified as parameter in file gridfinity_basic_cup.scad, line 177](https://github.com/ostat/gridfinity_extended_openscad/issues/177,D:/lsd/Downloads/gridfinity_extended_openscad-main%2015th%20Oct/gridfinity_extended_openscad-main/gridfinity_basic_cup.scad)
[WARNING: variable extension_tab_size not specified as parameter in file gridfinity_basic_cup.scad, line 177](https://github.com/ostat/gridfinity_extended_openscad/issues/177,D:/lsd/Downloads/gridfinity_extended_openscad-main%2015th%20Oct/gridfinity_extended_openscad-main/gridfinity_basic_cup.scad)

**Comment by lsd87** [comment]
I think using the gflabel program may be around the click label sizes since width and depth can be set so click (webb) default sizes can be over ridden.

usage: gflabel [-h] [--base {pred,plain,none,webb,predbox}] [--vscode] [-w WIDTH]
               [--height HEIGHT] [--depth DEPTH_MM] [--no-overheight] [-d DIVISIONS]
               [--font FONT]
               [--font-size-maximum FONT_SIZE_MAXIMUM | --font-size FONT_SIZE]
               [--font-style {regular,bold,italic}] [--margin MARGIN]
               [-o [OUTPUT ...]] [--style {embossed,debossed,embedded}]
               [--list-fragments] [--list-symbols] [--label-gap LABEL_GAP]
               [--column-gap COLUMN_GAP] [-v]
               LABEL [LABEL ...]

For me the various options are to
1). Drop the platform down when using click labels
2). I Gflabel set the sizes manually
3). Just use std labels and stick then in using double sided tape

The pret labels are 35.5mm long with 2 tabs making them 37.5mm long, would be nice to use them as well, would need a recess in the lip to take the two tabs - but this is a feature update :-)
https://www.printables.com/model/592545-gridfinity-bin-with-printable-label-by-pred-parame

**Comment by ostat** [comment]
> BTW. could you make the click label "eat" into the lip like the pret ones ?
I am sure we could. however it would require reworking how the label is implemented, and is not an easy fix.
The label is subtracted from the cavity, and then the cavity is subtracted from the filled in bin.
This means even if the label extends past the cavity it cant interfere with the wall or the lip of the bin. 
So we would need to find a clean way around this.

**Comment by lsd87** [comment]
I've been playing with gflabel and the problem with the normal platform is that even lowering the platform down by say 3mm, the rear had the rounded edges at the corners. SO you have to resize the platform so the label to comes out away from the rounded corners, or cut the corners off the label
![Normal corners](https://github.com/user-attachments/assets/7b05d5eb-bedb-4225-b435-142945be4cc3)

Using the click you have a square recess corners
![Click Corners](https://github.com/user-attachments/assets/798bbc30-93a2-4606-aa6e-842abba299a0)

Could you make the normal be like the click but without the 3 rails ?

**Comment by CullenJWebb** [comment]
@ostat The 2.0 version of the labels are ready here: https://github.com/CullenJWebb/Cullenect-Labels

They are being renamed "Cullenect" to differentiate between other swappable label types. Here are some of the features:

- Backward compatible with v1 bins (when generating 1u width labels)
- Variable label width
- Simpler geometry, easier to print and model.
- Emboss or deboss text
- More satisfying click
- Labels smaller than the socket can slide left and right along the new rail socket design
- Better vertical slot

And best of all it's been designed in OpenSCAD so that basic labels can be generated by users. Icons are still difficult in OpenSCAD though so I'm going to help get this implemented in gflabel as well.

**Comment by ostat** [comment]
I am going to close this ticket, as we have #20 still open that relates to adding support for the clicklabels
