### ISSUE TITLE
Labels - Left cup label position does not change

### ISSUE THREAD

**Issue by lsd87** [ostat/gridfinity_extended_openscad#54]
Using scad basic cup dated 12/oct/24 and openscad 30/oct/24

Created a 6 wide (1,2,3,4,5,6), 1 depth, 3 height cup, set vertical chambers to 3, just so to see where the labels get put
Set label size to 1 unit
For normal label style, left = left, right=left, center=left ie. the label just stays in the left cup (no.1)
Setting leftchamber all 3 double cups have labels on the left(1,3,5)
rightchamber gives cup 1&2 left, cups 3&4 right and cups 4&5 right sort of what you'd expect, except for cups 1&2
centerchamber give the same, cups 3&4 and 5&6 in the center  and 1&2 label stays in the left
Same for click style

![image](https://github.com/user-attachments/assets/63016c9f-b201-4d62-b354-7116a7f74bcc)

**Comment by ostat** [comment]
thanks for raising, this was fixed in b0c6212

![image](https://github.com/user-attachments/assets/036b8728-e7fb-459c-b84e-20b9f40949ca)
