### ISSUE TITLE
Normal labels, right recess wall missing

### ISSUE THREAD

**Issue by lsd87** [ostat/gridfinity_extended_openscad#55]
The right recess mini wall appears missing, is this meant to be this way, maybe ?

![image](https://github.com/user-attachments/assets/e7bed808-01c0-410a-8642-8ac1e249ee4c)

**Comment by ostat** [comment]
thanks, I missed that in the label redactor for the click labels.
fixed in 3a5d44b
![image](https://github.com/user-attachments/assets/994945e3-8df0-4ad3-80a1-de7b3ed55e15)
