### ISSUE TITLE
Baseplate issues

### ISSUE THREAD

**Issue by elbelga** [ostat/gridfinity_extended_openscad#6]
I dont not why but baseplate is cut on both sides

<img width="984" alt="image" src="https://github.com/ostat/gridfinity_extended_openscad/assets/1613259/69a401e6-b35c-43ee-b1d6-180895b5cdd1">

**Comment by elbelga** [comment]
I have the latest version 
<img width="577" alt="image" src="https://github.com/ostat/gridfinity_extended_openscad/assets/1613259/86811ecb-f932-4c79-87a2-86a64ec60c86">

I set the same config but it doesnt works properly
<img width="1326" alt="image" src="https://github.com/ostat/gridfinity_extended_openscad/assets/1613259/2328c13c-a41f-4de1-893f-9e289f0d7701">


I dont know if it is related but I have this warnings in console

`
[WARNING: Ignoring unknown variable 'butterflyClipEnabled' in file gridfinity_baseplate.scad, line 191](https://github.com/ostat/gridfinity_extended_openscad/issues/191,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable 'butterflyClipSize' in file gridfinity_baseplate.scad, line 192](https://github.com/ostat/gridfinity_extended_openscad/issues/192,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable 'butterflyClipRadius' in file gridfinity_baseplate.scad, line 193](https://github.com/ostat/gridfinity_extended_openscad/issues/193,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable 'filamentClipEnabled' in file gridfinity_baseplate.scad, line 194](https://github.com/ostat/gridfinity_extended_openscad/issues/194,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable 'filamentClipDiameter' in file gridfinity_baseplate.scad, line 195](https://github.com/ostat/gridfinity_extended_openscad/issues/195,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable 'filamentClipLength' in file gridfinity_baseplate.scad, line 196](https://github.com/ostat/gridfinity_extended_openscad/issues/196,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable '$idx' in file gridfinity_baseplate.scad, line 458](https://github.com/ostat/gridfinity_extended_openscad/issues/458,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable '$idx' in file gridfinity_baseplate.scad, line 458](https://github.com/ostat/gridfinity_extended_openscad/issues/458,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable '$idx' in file gridfinity_baseplate.scad, line 460](https://github.com/ostat/gridfinity_extended_openscad/issues/460,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad) 
[WARNING: Ignoring unknown variable '$idx' in file gridfinity_baseplate.scad, line 461](https://github.com/ostat/gridfinity_extended_openscad/issues/461,/Users/belga/Documents/gridfinity_extended_openscad/gridfinity_baseplate.scad)
`

**Comment by elbelga** [comment]
I believe is a problem with OpenScad version, with snapshot version works well

**Comment by ostat** [comment]
Thanks for letting me know. 
I think I can add a check for the version, so the issue is clearer.

**Comment by ostat** [comment]
I have added a check to assert version of OpenSCAD

**Comment by lied** [comment]
can you please put a info to the repo readme that the version of OpenSCAD needs to be the snapshot version? I've had the same issue (Mac OSX).
