### ISSUE TITLE
Subdivision separators float above floor using flat base

### ISSUE THREAD

**Issue by rwgunther** [ostat/gridfinity_extended_openscad#60]
When I create a basic cup with subdivisions, the separators don't go all the way down to the floor if you use the **flat base** option. I've found that I can work around this by enabling the **efficient floor** option, but I'm thinking this is probably a bug. I've tried it both in MakerWorld's customizer and locally in OpenSCAD.

![Screenshot 2024-11-15 at 12 26 41 PM](https://github.com/user-attachments/assets/7551d321-53fe-4ac9-bb8b-63e4a37ad16e)
![Screenshot 2024-11-15 at 1 53 04 PM](https://github.com/user-attachments/assets/a6f38b2c-f219-46cc-890b-e733d9516eef)

**Comment by ostat** [comment]
I believe this is now fixed, its not yet uploaded to makerworld, will do that soon.
![image](https://github.com/user-attachments/assets/31ba5f3d-f021-4b72-a0c6-a32f1a01a3e9)

**Comment by rwgunther** [comment]
Excellent! I'll check it out. Thanks.

**Comment by ostat** [comment]
believed to be fixed
