### ISSUE TITLE
Bug?: Separator Cuts into Label

### ISSUE THREAD

**Issue by AlansCodeLog** [ostat/gridfinity_extended_openscad#62]
First, I want to say amazing project!

I ran into a little issue with the separators and the labels. Not sure if I'm missing something but they cut into the label and don't take into account the label relief. This is also true of the click labels. I thought their height might be customizable via the custom config but it isn't either. I've quickly just edited the code for myself and subtracted what I needed in calculateSeparators.
![image](https://github.com/user-attachments/assets/d22ed074-cd72-40c7-a3d8-3129af64ad7c)

**Comment by ostat** [comment]
This is a know issue. I try to auto account for conflict of different features, but sometimes its not really possible.
In this case as you have shown depending on the label, the wall might interfere with the label cavity.

Under the subdivision section, there is an option for `chamber wall zClearance`. This will reduce the wall by the required amount.
![image](https://github.com/user-attachments/assets/c647dcf6-42bd-4cc2-82b6-7d219f56f20c)
