### ISSUE TITLE
Feature request: option to disable rounded outside corners for the baseplate

### ISSUE THREAD

**Issue by jziolkowski** [ostat/gridfinity_extended_openscad#72]
Since custom grid is not compatible with the newly improved fill mode for fractional grids, it'd be nice to either toggle all rounded outside edges of the plate, or apply the same 4-bit array to control which ones are round?

**Comment by ostat** [comment]
I was not sure if anyone really used the custom grids. I liked the 4bit array, but it was kinda complex, I would like to make it auto calculate but have not tried to create that logic.

What kind of shape were you trying to create?

**Comment by jziolkowski** [comment]
Like this, but with marked edges being straight, not rounded
![image](https://github.com/user-attachments/assets/d41ed17a-f361-4f15-85fd-718d56fa01f4)

**Comment by ostat** [comment]
using the bitwise style option would not be easy for this. Also there are some issue with cropping I would need to deal with.

I have added an option to set the plate corner radius. I think this is what you want?
![image](https://github.com/user-attachments/assets/2c5f67ed-b978-416b-a439-6aecf61a3fce)

**Comment by jziolkowski** [comment]
This is more than enough! Fantastic. Thanks!
