### ISSUE TITLE
Error rendering gridfinity_sliding_lid.scad

### ISSUE THREAD

**Issue by jrichman-r7** [ostat/gridfinity_extended_openscad#74]
Getting the following error when attempting to render in lid mode: 
`[ERROR: Assertion '(is_list(value) && (len(value) == 2))' failed: "42 should be array of length 2" in file modules/functions_gridfinity.scad, line 11]`

I spent the afternoon troubleshooting and ran into some curious issues. When print debugging in `functions_gridfinity.scad`, `width` and `depth` are properly stored as vectors and have expected values as defined in `gridfinity_sliding_lid.scad`, but when passed into the `calcDimension` function, `value` becomes undefined.

I set values manually for `width` and `depth` eg.
```
function calcDimensionWidth(width, shouldLog = false) = calcDimension([2,0], "width", gf_pitch, shouldLog);
function calcDimensionDepth(depth, shouldLog = false) = calcDimension([2,0], "depth", gf_pitch, shouldLog);
``` 
and the render worked just fine.

Not sure if I'm missing something here, but wanted to share my findings/ask for help! Thanks in advance :)

PS I'm using OpenSCAD version 2024.10.07 on an ARM-based Mac. (Also tested with version 2024.11.27 and 2021.01, same issue).

**Comment by ostat** [comment]
Hi thanks for raising and providing as much detail as you did.
This has been fixed.
![image](https://github.com/user-attachments/assets/e8f3eaf6-98e7-4d46-8d57-a75bf5dce094)
