### ISSUE TITLE
Improved mounting system for drawer chests

### ISSUE THREAD

**Issue by Monniasza** [ostat/gridfinity_extended_openscad#82]
Hi. Yesterday I've completed a 22-hour print of a drawer chest from your generator, but the supports generated by OrcaSlicer stuck way too strong and needed tools to remoce them. My printer is 22×22 cm and the chest is about 18×18 cm, so I couldn't fit fancy tree supports. After trying to remove supports, the chest was left damaged. I want to add the optimized mounts from [Gridfinity Modular Drawer System](https://www.printables.com/model/300896-gridfinity-modular-drawer-system) with a tiny support fin for each of the male mounts, so no supports are required in the slicer. As in the title, I'll make a PR and link it here to add these mounts.

**Comment by ostat** [comment]
This has been merged.
