### ISSUE TITLE
Drawer top plate is the same whether it is default or efficient magnet base

### ISSUE THREAD

**Issue by Monniasza** [ostat/gridfinity_extended_openscad#86]
Hi. When I pulled your last commit, the drawers chest always has the efficient magnet base. This happens on both of my repositories.

**Comment by Monniasza** [comment]
![image](https://github.com/user-attachments/assets/b3d12bd2-7463-4443-b9bf-9046579e9d4d)
![image](https://github.com/user-attachments/assets/486613cd-92c5-4d75-b8f0-79f71ef7c626)

**Comment by ostat** [comment]
I rewrote the base script, I will need to update the cheat options to align. 

I replaced the old list of base types with individual options for each feature. 
So you no longer pick the magnet base or weighted base, you now enable or disable the magnets. This allows for more flexibility.

**Comment by Monniasza** [comment]
Concerning #83 and #82, I've removed the top plate and base checkboxes and used the list only, with the "None" option disabling top plates and bases respectively.

**Comment by Monniasza** [comment]
@ostat After merging the #84, this issue persists.

**Comment by ostat** [comment]
That is a different issue than what the resolved. 
It's not fixed yet. 
I will try fix it this week.
I also want to use some of the new features to further improve the way the grid is used in chest. 
I will let you know when it's done so you can try it out.

**Comment by Monniasza** [comment]
@ostat Have you fixed it?

**Comment by ostat** [comment]
The updated baseplate has been incorporated in to chest,

This fixes the magnet option, fills the space around the baseplate to make it look cleaner and print easier, fixed some issues with the placement of plate in the drawers.

![image](https://github.com/user-attachments/assets/9c2f34b1-31ff-40f8-83c0-d09bdd782c7a)

**Comment by Monniasza** [comment]
It's fixed.
![image](https://github.com/user-attachments/assets/4bc93837-54c7-4814-baa1-c27fb7f97768)
