### ISSUE TITLE
Drawer and chest clearance options are unclear

### ISSUE THREAD

**Issue by Monniasza** [ostat/gridfinity_extended_openscad#87]
Hi. Recently I've noticed that you have added more options for content-to-drawer and drawer-to-chest clearance options, but I can't understand what each column means. You should update the descriptions to match the real meaning of the options.

**Comment by ostat** [comment]
Agreed, also the doco needs updating. Just need more time.

**Comment by Monniasza** [comment]
@ostat Please add labels, you have removed tags from the title.

**Comment by ostat** [comment]
I have updated the comments to make them clearer. 9071ab4

**Comment by Monniasza** [comment]
@ostat It's clear now.
